Add InvalidMiddlewareDefinitionException + Improve tests + Update dev dependencies
yiisoft/middleware-dispatcher pull request #14
Opened 2021-01-03 20:15 UTC by vjik

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | -

2021-01-12 09:41 UTC, samdark requested changes

2021-01-12 09:41 UTC, samdark commented on src/InvalidMiddlewareDefinitionException.php
> +        }
```suggestion
        $definitionString = $this->convertDefinitionToString($middlewareDefinition);
        if ($definitionString !== null) {
            $message .= ' Got ' . $definitionString . '.';
        }
```

2021-01-12 09:41 UTC, samdark commented on src/InvalidMiddlewareDefinitionException.php
> +            return 'Instance of class "' . get_class($middlewareDefinition) . '"';
```suggestion
            return 'an instance of "' . get_class($middlewareDefinition) . '"';
```

2021-01-12 09:41 UTC, samdark commented on tests/InvalidMiddlewareDefinitionExceptionTest.php
> +        $this->assertStringEndsWith('. Got it: ' . $expected . '.', $exception->getMessage());
```suggestion
        $this->assertStringEndsWith('. Got ' . $expected . '.', $exception->getMessage());
```

2021-01-12 09:41 UTC, samdark commented on tests/InvalidMiddlewareDefinitionExceptionTest.php
> +                'Instance of class "Yiisoft\Middleware\Dispatcher\Tests\Support\TestController"',
```suggestion
                'an instance of "Yiisoft\Middleware\Dispatcher\Tests\Support\TestController"',
```

2021-01-15 20:10 UTC, vjik commented on src/InvalidMiddlewareDefinitionException.php
> +        }
Done.

2021-01-15 20:10 UTC, vjik commented on src/InvalidMiddlewareDefinitionException.php
> +            return 'Instance of class "' . get_class($middlewareDefinition) . '"';
Done.

2021-01-15 20:10 UTC, vjik commented on tests/InvalidMiddlewareDefinitionExceptionTest.php
> +        $this->assertStringEndsWith('. Got it: ' . $expected . '.', $exception->getMessage());
Done.

2021-01-15 20:10 UTC, vjik commented on tests/InvalidMiddlewareDefinitionExceptionTest.php
> +                'Instance of class "Yiisoft\Middleware\Dispatcher\Tests\Support\TestController"',
Done.

2021-01-20 14:03 UTC, samdark approved these changes

2021-01-20 14:03 UTC, merged

2021-01-20 14:03 UTC, samdark commented
👍