Implement friendly exception for `InvalidMiddlewareDefinitionException`
yiisoft/middleware-dispatcher pull request #50
Opened 2022-05-30 13:33 UTC by vjik

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #45

Screenshotes:
![image](https://user-images.githubusercontent.com/525501/171002938-ffbb9e45-5125-43eb-8744-844bc81253be.png)
![image](https://user-images.githubusercontent.com/525501/171003018-686e01b8-1847-4a21-b3d3-f0bb9c50f409.png)
![image](https://user-images.githubusercontent.com/525501/171003065-df55beae-7072-4e2c-8d81-f7b161e978aa.png)

2022-05-30 14:16 UTC, samdark requested changes

2022-05-30 14:16 UTC, samdark commented on src/InvalidMiddlewareDefinitionException.php
> +            Class `{$this->definition[0]}` exist, but not contain method `{$this->definition[1]}()`.
```suggestion
            Class `{$this->definition[0]}` exists, but does not contain method `{$this->definition[1]}()`.
```

2022-05-30 14:16 UTC, samdark commented on src/InvalidMiddlewareDefinitionException.php
> +            Try add action `{$this->definition[1]}()` to controller `{$this->definition[0]}`:
```suggestion
            Try to add `{$this->definition[1]}()` action to `{$this->definition[0]}` controller:
```

2022-05-30 14:16 UTC, samdark commented on src/InvalidMiddlewareDefinitionException.php
> +                // TODO: Implement you action
```suggestion
                // TODO: Implement your action
```

2022-05-30 14:16 UTC, samdark commented on src/InvalidMiddlewareDefinitionException.php
> +                'Class `%s` exists, but not implement `%s`.',
```suggestion
                'Class `%s` exists, but does not implement `%s`.',
```

2022-05-30 14:16 UTC, samdark commented on src/InvalidMiddlewareDefinitionException.php
> +                'Class `%s` not found. It may be need to install a package with this middleware.',
```suggestion
                'Class `%s` not found. It may be needed to install a package with this middleware.',
```

2022-05-30 14:16 UTC, samdark commented on tests/InvalidMiddlewareDefinitionExceptionTest.php
> +                'Class `Yiisoft\Middleware\Dispatcher\Tests\Support\TestController` exists, but not implement',
```suggestion
                'Class `Yiisoft\Middleware\Dispatcher\Tests\Support\TestController` exists, but does not implement',
```

2022-05-30 14:16 UTC, samdark commented on tests/InvalidMiddlewareDefinitionExceptionTest.php
> +                'Try add action `notExistsAction()` to controller ',
```suggestion
                'Try adding action `notExistsAction()` to controller ',
```

2022-06-01 13:52 UTC, vjik commented on src/InvalidMiddlewareDefinitionException.php
> +            Class `{$this->definition[0]}` exist, but not contain method `{$this->definition[1]}()`.
done

2022-06-01 13:52 UTC, vjik commented on src/InvalidMiddlewareDefinitionException.php
> +                // TODO: Implement you action
done

2022-06-01 13:52 UTC, vjik commented on src/InvalidMiddlewareDefinitionException.php
> +                'Class `%s` exists, but not implement `%s`.',
done

2022-06-01 13:52 UTC, vjik commented on tests/InvalidMiddlewareDefinitionExceptionTest.php
> +                'Class `Yiisoft\Middleware\Dispatcher\Tests\Support\TestController` exists, but not implement',
done

2022-06-01 13:53 UTC, vjik commented
![image](https://user-images.githubusercontent.com/525501/171421356-b041c108-b21f-4eb9-9d76-368da44fdecb.png)

2022-06-07 13:45 UTC, merged